### ISSUE TITLE
Unable to update a Google Spreadsheet through Hub Action step

### ISSUE THREAD

**Issue by pmallol** [instedd/mbuilder#284] opened 2015-03-02 20:15 UTC
Found in mBuilder version 1.2-pre2
(Hub version 1a700c0)

Precondition:
User has:
- a Google Spreadsheet "X" with a column "phone_number" listing a series of number -one of them '12345'- and another empty column "text"
- Google Spreadsheet connector already configured in Hub

1. Create a message trigger and add a name
2. Fill the message input field with phrase: "update [123] with [text]" and transform "123" and "text" to pills  highlighting them
3. Add a Hub Action step in which the Google Spreadsheet "X" is updated
4. Drag and drop pill [123] in 'filter: phone_number' and pill [text] in 'properties: text'
5. Test the message trigger with the Sandbox writing "update 12345 with Foo"

Obtained: the action "Invoke hub action" is performed but the GSpreadsheet "X" is not updated

Expected: the GSpreadsheet is updated and the row for number "12345" says "Foo" next to it

![screen shot 2015-03-02 at 4 53 22 pm](https://cloud.githubusercontent.com/assets/9214460/6449418/4d08dfd8-c0ff-11e4-97e0-36fe9a18409d.png)
![screen shot 2015-03-02 at 5 12 41 pm](https://cloud.githubusercontent.com/assets/9214460/6449428/5cae50f8-c0ff-11e4-9c4e-7bc313f13a63.png)

**Comment by vtiffenberg** [comment] 2015-03-19 18:02
The problem is not with the mBuilder update, but inside Hub's GoogleSpreadsheet connector: mBuilder is sending the number [123] as a number and spreadsheet cells are only strings. So when the comparison is being made there's a type mismatch and the correct row to update isn't being found. 

@nditada : Should I make that search in Hub work for Integers, Floats and Strings? On this side, this issue can be closed

**Comment by nditada** [comment] 2015-03-19 19:06
Yes, let's close this issue and open one in Hub.

**Closed** 2015-03-19 19:11 UTC
Labels: blocker, bug

**Comment by pmallol** [comment] 2015-03-30 14:56
Ok in version 1.2-pre3 and Hub version 511b47e
